# Generated by Django 2.2.1 on 2019-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineral_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineral',
            old_name='optical_properities',
            new_name='optical_properties',
        ),
    ]
