# Generated by Django 2.2.1 on 2019-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral_catalog', '0002_auto_20190514_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(default='', max_length=255),
        ),
    ]
